export const CarsData =[
    {
        id: 1,
        image: "./images/Cars/1.png",
        title: "Land Rover, Range Rover Car",
        cat: "cars",
        price: "3500",
    },
    {
        id: 2,
        image: "./images/Cars/2.png",
        title:"Mercedes Car",
        cat: "cars",
        price: "3500",
    },
    {
        id: 3,
        image: "./images/Cars/3.png",
        title: "Bluw Bnw Car",
        cat: "cars",
        price: "2400",
    },
    {
        id: 4,
        image: "./images/Cars/4.png",
        title: "Papua New Guinea",
        cat: "cars",
        price: "5000",
    },
    {
        id: 5,
        image: "./images/Cars/5.png",
        title: "Red Hyundai Car",
        cat: "cars",
        price: "2500",
    },
    {
        id: 6,
        image: "./images/Cars/6.jpg",
        title: "Bmw Car",
        cat: "cars",
        price: "6500",
    },
    {
        id: 7,
        image: "./images/Cars/7.png",
        title: "Audi Jeep",
        cat: "cars",
        price: "4500",
    },
    {
        id: 8,
        image: "./images/Cars/8.png",
        title: "Porsche Car",
        cat: "cars",
        price: "5500",
    },
]
export const ElectronicData = [
    {
        id: 9,
        image: "./images/Electronic/1.jpg",
        title: "Samsung 65 Inch 4K UHD Smart LED TV",
        cat: "Electronic",
        price: "299",
    },
    {
        id: 10,
        image: "./images/Electronic/2.jpg",
        title: "Toshiba LED 43 Inch Full HD TV ",
        cat: "Electronic",
        price: "450",
    },
    {
        id: 11,
        image: "./images/Electronic/3.jpg",
        title: "LG LED Smart TV 43 inch",
        cat: "Electronic",
        price: "290",
    },
    {
        id: 12,
        image: "./images/Electronic/4.jpg",
        title: "LG 43 Inch FHD LED TV",
        cat: "Electronic",
        price: "300",
    },
    {
        id: 13,
        image: "./images/Electronic/5.jpg",
        title: "iQ&T N6-6.1-inch ",
        cat: "Electronic",
        price: "150",
    },
    {
        id: 14,
        image: "./images/Electronic/6.jpg",
        title: "iPhone 13 Pro Max ",
        cat: "Electronic",
        price: "3500",
    },
    {
        id: 15,
        image: "./images/Electronic/7.jpg",
        title: "Nokia 150 Dual",
        cat: "Electronic",
        price: "250",
    },
    {
        id: 16,
        image: "./images/Electronic/8.jpg",
        title: "Samsung Galaxy A12",
        cat: "Electronic",
        price: "350",
    },
    {
        id: 17,
        image: "./images/Electronic/9.jpg",
        title: "iPhone 11 Pro Max ",
        cat: "Electronic",
        price: "500",
    },
]
export const ClothesData = [
    {
        id: 18,
        image: "./images/Clothes/1.jpg",
        title: "'Hello Kitty' kit",
        cat: "Clothes",
        price: "125",
    },
    {
        id: 19,
        image: "./images/Clothes/2.jpg",
        title: "Two-piece cotton jumpsuit",
        cat: "Clothes",
        price: "99",
    },
    {
        id: 20,
        image: "./images/Clothes/3.jpg",
        title: "Buddy Basic Bay",
        cat: "Clothes",
        price: "125",
    },
    {
        id: 21,
        image: "./images/Clothes/4.jpg",
        title: "CAPSHOW CUT T-shirt",
        cat: "Clothes",
        price: "35",
    },
    {
        id: 22,
        image: "./images/Clothes/5.jpg",
        title: "pajama pants",
        cat: "Clothes",
        price: "200",
    },
    {
        id: 23,
        image: "./images/Clothes/6.jpg",
        title: "Lycra bungee pants",
        cat: "Clothes",
        price: "100",
    },
    {
        id: 24,
        image: "./images/Clothes/7.jpg",
        title: "Short",
        cat: "Clothes",
        price: "25",
    },
    {
        id: 25,
        image: "./images/Clothes/8.jpg",
        title: "Cotton T-shirts with neck",
        cat: "Clothes",
        price: "100",
    },
    {
        id: 26,
        image: "./images/Clothes/9.jpg",
        title: "Athletic Pants",
        cat: "Clothes",
        price: "150",
    },
    {
        id: 27,
        image: "./images/Clothes/10.jpg",
        title: "trunge deer",
        cat: "Clothes",
        price: "50",
    },
    {
        id: 28,
        image: "./images/Clothes/11.jpg",
        title: "Abaya Dress",
        cat: "Clothes",
        price: "199",
    },
]
export const FashonData = [
    {
        id: 29,
        image: "./images/Fashon/1.jpg",
        title: "Fashion store",
        cat: "Fashon",
        price: "299",
    },
    {
        id: 30,
        image: "./images/Fashon/2.jpg",
        title: "Athletic Shoe",
        cat: "Fashon",
        price: "99",
    },
    {
        id: 31,
        image: "./images/Fashon/3.jpg",
        title: "Sunglasses",
        cat: "Fashon",
        price: "50",
    },
    {
        id: 32,
        image: "./images/Fashon/4.jpg",
        title: "Metal watch",
        cat: "Fashon",
        price: "99",
    },
    {
        id: 33,
        image: "./images/Fashon/5.jpg",
        title: "Men leather casual",
        cat: "Fashon",
        price: "88",
    },
    {
        id: 34,
        image: "./images/Fashon/6.jpg",
        title: "Canvas shoes",
        cat: "Fashon",
        price: "50",
    },
    {
        id: 35,
        image: "./images/Fashon/7.jpg",
        title: "medical glasses",
        cat: "Fashon",
        price: "30",
    },
    {
        id: 36,
        image: "./images/Fashon/8.jpg",
        title: "Apple Watch Series",
        cat: "Fashon",
        price: "199",
    },
    {
        id: 37,
        image: "./images/Fashon/9.jpg",
        title: "Cards store",
        cat: "Fashon",
        price: "15",
    },
    {
        id: 38,
        image: "./images/Fashon/10.jpg",
        title: "Frederique Constant",
        cat: "Fashon",
        price: "299",
    },
]
